package actions

import (
	"fmt"
	"net/http"
	"oss_inventory/models"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Component)
// DB Table: Plural (components)
// Resource: Plural (Components)
// Path: Plural (/components)
// View Template Folder: Plural (/templates/components/)

// ComponentsResource is the resource for the Component model
type ComponentsResource struct {
	buffalo.Resource
}

// List gets all Components. This function is mapped to the path
// GET /components
func (v ComponentsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	components := &models.Components{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Components from the DB
	if err := q.All(components); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("components", components)
		return c.Render(http.StatusOK, r.HTML("/components/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(components))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(components))
	}).Respond(c)
}

// Show gets the data for one Component. This function is mapped to
// the path GET /components/{component_id}
func (v ComponentsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Component
	component := &models.Component{}

	// To find the Component the parameter component_id is used.
	if err := tx.Find(component, c.Param("component_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("component", component)

		return c.Render(http.StatusOK, r.HTML("/components/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(component))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(component))
	}).Respond(c)
}

// New renders the form for creating a new Component.
// This function is mapped to the path GET /components/new
func (v ComponentsResource) New(c buffalo.Context) error {
	c.Set("component", &models.Component{})

	return c.Render(http.StatusOK, r.HTML("/components/new.plush.html"))
}

// Create adds a Component to the DB. This function is mapped to the
// path POST /components
func (v ComponentsResource) Create(c buffalo.Context) error {
	// Allocate an empty Component
	component := &models.Component{}

	// Bind component to the html form elements
	if err := c.Bind(component); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.Eager().ValidateAndCreate(component)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("component", component)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/components/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "component.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/components/%v", component.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(component))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(component))
	}).Respond(c)
}

// Edit renders a edit form for a Component. This function is
// mapped to the path GET /components/{component_id}/edit
func (v ComponentsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Component
	component := &models.Component{}

	if err := tx.Find(component, c.Param("component_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("component", component)
	return c.Render(http.StatusOK, r.HTML("/components/edit.plush.html"))
}

// Update changes a Component in the DB. This function is mapped to
// the path PUT /components/{component_id}
func (v ComponentsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Component
	component := &models.Component{}

	if err := tx.Find(component, c.Param("component_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Component to the html form elements
	if err := c.Bind(component); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(component)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("component", component)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/components/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "component.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/components/%v", component.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(component))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(component))
	}).Respond(c)
}

// Destroy deletes a Component from the DB. This function is mapped
// to the path DELETE /components/{component_id}
func (v ComponentsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Component
	component := &models.Component{}

	// To find the Component the parameter component_id is used.
	if err := tx.Find(component, c.Param("component_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(component); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "component.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/components")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(component))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(component))
	}).Respond(c)
}
